[project]
name = "clarity-simple-nft"
authors = ["Your Name"]
description = "A simple NFT implementation in Clarity 2.0"
telemetry = false
requirements = []
analysis = ["check_checker"]
costs_version = 2

[contracts.simple-nft]
path = "contracts/simple-nft.clar"
depends_on = []

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
